Minor changes in CC
arivazhagan-tmm/Bend-Assist pull request #28
Opened 2024-07-11 09:44 UTC by Harshini-Jesi

2024-07-11 11:10 UTC, arivazhagan-tmm requested changes

2024-07-11 11:10 UTC, arivazhagan-tmm commented on Src/BendAssist.App/BendAssists/CornerClose.cs
> +            var (line1, line2) = (connectedPLines[0], connectedPLines[1]);
this could be simplified as follows, 
var (line1, line2) = ((PLine)connectedPLines[0], (PLine)connectedPLines[1]);
if (line1.Index != line2.Index - 1) mStepLines.AddRange([line1, line2]);

2024-07-11 11:10 UTC, arivazhagan-tmm commented on Src/BendAssist.App/BendAssists/CornerClose.cs
> +               mNewLines.Add (new (translatedLine.StartPoint, translatedLine.EndPoint, ++mIndex));
var (dx, dy) = pLine.Orientation switch {
   Horizontal => startPt.Y < centroid.Y ? (0.0, lineShift) : (0.0, -lineShift),
   Vertical => startPt.X < centroid.X ? (lineShift, 0.0) : (-lineShift, 0.0),
   _ => (0.0, 0.0),
};
var vect = new Vector2 (dx, dy);
mNewLines.Add (new (pLine.StartPoint + vect, pLine.EndPoint + vect, ++mIndex));

2024-07-11 11:10 UTC, arivazhagan-tmm commented on Src/BendAssist.App/BendAssists/CornerClose.cs
>                 mNewLines.Add (new (trimmedEdge.StartPoint, trimmedEdge.EndPoint, ++mIndex));
var (startDx, startDy, endDx, endDy) = (0.0, 0.0, 0.0, 0.0);
if (mStepStartPts.Contains (endPt) && mStepEndPts.Contains (startPt)) {
      (startDx, startDy, endDx, endDy) = pLine.Orientation switch {
      Horizontal => startPt.Y < centroid.Y ? (-halfBD, -lineShift, 0.0, 0.0) : (halfBD, lineShift, 0.0, 0.0),
      Vertical => startPt.X < centroid.X ? (0.0, halfBD, 0.0, lineShift) : (0.0, -halfBD, 0.0, -lineShift),
      _ => (0.0, 0.0, 0.0, 0.0)
   };
   trimmedEdge = (PLine)pLine.Trimmed (startDx, startDy, endDx, endDy);
   mNewLines.Add (new (trimmedEdge.StartPoint, trimmedEdge.EndPoint, ++mIndex));

2024-07-17 06:45 UTC, Harshini-Jesi commented on Src/BendAssist.App/BendAssists/CornerClose.cs
>                 mNewLines.Add (new (trimmedEdge.StartPoint, trimmedEdge.EndPoint, ++mIndex));
I have done this in a different way. Please check if it's fine.

2024-07-17 10:59 UTC, merged